config/routes.rb
PetStars::Application.routes.draw do
  devise_for :users

  get "pages/info"

  root :to => redirect('/pets')
  resources :pets

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  mount_uploader :description, PictureUploader
  attr_accessible :animal, :description, :dob, :owneremail, :ownername, :petid, :petname
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pets }
    end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @pet = Pet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pet }
    end
  end

  # GET /pets/new
  # GET /pets/new.json
  def new
    @pet = Pet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pet }
    end
  end

  # GET /pets/1/edit
  def edit
    @pet = Pet.find(params[:id])
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(params[:pet])

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render json: @pet, status: :created, location: @pet }
      else
        format.html { render action: "new" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pets/1
  # PUT /pets/1.json
  def update
    @pet = Pet.find(params[:id])

    respond_to do |format|
      if @pet.update_attributes(params[:pet])
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetStars</title>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Pet Stars app</a>
      <ul class="nav">
        <li class="active"><a href="/pets">Pets</a></li>
      </ul>
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>

<footer>
  <div class="container">
    Desperate Dan 2013
  </div>
</footer>

</body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>

<h2>Pets Stars</h2>

Your pet has a horoscope too!!

Enter your pet details and find out what the future
holds for your pet.

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :petname %><br />
    <%= f.text_field :petname %>
  </div>
  <div class="field">
    <%= f.label :animal %><br />
    <%= f.text_field :animal %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.file_field :description %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob, :start_year => 1980, :end_year => 2013%>
  </div>
  <div class="field">
    <%= f.label :ownername %><br />
    <%= f.text_field :ownername %>
  </div>
  <div class="field">
    <%= f.label :owneremail %><br />
    <%= f.text_field :owneremail %>
  </div>
  <div class="field">
    <%= f.label :petid %><br />
    <%= f.number_field :petid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Listing pets</h1>

<table>
  <tr>
    <th>Petname</th>
    <th>Animal</th>
    <th>Description</th>
    <th>Dob</th>
    <th>Ownername</th>
    <th>Owneremail</th>
    <th>Petid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pets.each do |pet| %>
  <tr>
    <td><%= pet.petname %></td>
    <td><%= pet.animal %></td>
    <td><%= pet.description %></td>
    <td><%= pet.dob %></td>
    <td><%= pet.ownername %></td>
    <td><%= pet.owneremail %></td>
    <td><%= pet.petid %></td>
    <td><%= link_to 'Show', pet %></td>
    <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
    <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Petname:</b>
  <%= @pet.petname %>
</p>

<p>
  <b>Animal:</b>
  <%= @pet.animal %>
</p>

<p>
  <b>Description:</b>
  <%= image_tag(@pet.description_url, :width => 600) if @pet.description.present? %>
</p>

<p>
  <b>Dob:</b>
  <%= @pet.dob %>
</p>

<p>
  <b>Ownername:</b>
  <%= @pet.ownername %>
</p>

<p>
  <b>Owneremail:</b>
  <%= @pet.owneremail %>
</p>

<p>
  <b>Petid:</b>
  <%= @pet.petid %>
</p>


<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>